version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: waterpolo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: waterpolo
      POSTGRES_PASSWORD: waterpolo_password_123
      POSTGRES_DB: waterpolo_stats
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waterpolo"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waterpolo-app
    restart: unless-stopped
    ports:
      - "3011:3000"
    environment:
      DATABASE_URL: "postgresql://waterpolo:waterpolo_password_123@postgres:5432/waterpolo_stats?schema=public"
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy &&
         node server.js"

volumes:
  postgres_data:
